// ── 番茄人生 Obsidian 插件 — 数据持久化层 ──
// 方案A：所有数据以 .md 文件存入 vault，Agent 可直接读取

import { App, TFile, TFolder } from 'obsidian';
import { GtdItem, TaskItem, Session, TomatoSettings, DEFAULT_SETTINGS } from './types';

export class DataManager {
  app: App;
  settings: TomatoSettings;

  constructor(app: App, settings: TomatoSettings) {
    this.app = app;
    this.settings = settings;
  }

  // ═══════════════════════ 设置 ═══════════════════════

  async loadSettings(): Promise<TomatoSettings> {
    return { ...DEFAULT_SETTINGS, ...this.settings };
  }

  // ═══════════════════════ Session 日志 ═══════════════════

  /** 获取今天的日期字符串 YYYY-MM-DD */
  getTodayStr(): string {
    return new Date().toISOString().slice(0, 10);
  }

  /** 日志文件路径 */
  getLogPath(dateStr?: string): string {
    const base = this.settings.exportPath || 'Pomodoro Logs';
    return `${base}/${dateStr || this.getTodayStr()}.md`;
  }

  /** 确保导出目录存在 */
  async ensureFolder(): Promise<void> {
    const base = this.settings.exportPath || 'Pomodoro Logs';
    const parts = base.split('/');
    let current = '';
    for (const part of parts) {
      current += (current ? '/' : '') + part;
      const folder = this.app.vault.getAbstractFileByPath(current);
      if (!folder) {
        await this.app.vault.createFolder(current);
      }
    }
  }

  /** 创建新的每日日志文件（含所有段落模板） */
  private makeLogTemplate(dateStr: string): string {
    return [
      `# Pomodoro Log — ${dateStr}`,
      '',
      '> Generated by Pomodoro',
      '',
      '---',
      '',
      `## Sessions — ${dateStr}`,
      '',
      `## Completed Tasks — ${dateStr}`,
      '',
      `## Completed GTD — ${dateStr}`,
      '',
      '---',
      '',
    ].join('\n');
  }

  /** 向每日日志的指定段落追加一行 */
  async appendToLog(section: string, entry: string): Promise<void> {
    await this.ensureFolder();
    const dateStr = this.getTodayStr();
    const path = this.getLogPath();
    let file = this.app.vault.getAbstractFileByPath(path) as TFile | null;

    const sectionHeader = `## ${section} — ${dateStr}`;

    if (!file) {
      // 新建文件，在对应段落下插入条目
      let template = this.makeLogTemplate(dateStr);
      template = template.replace(
        sectionHeader + '\n\n',
        sectionHeader + '\n\n' + entry + '\n'
      );
      await this.app.vault.create(path, template);
      return;
    }

    let content = await this.app.vault.read(file);

    // 查找段落标题
    const sectionIdx = content.indexOf(sectionHeader);
    if (sectionIdx >= 0) {
      // 段落已存在：找到下一个 ## 或 --- 作为插入边界
      const afterHeader = content.indexOf('\n', sectionIdx) + 1;
      const rest = content.slice(afterHeader);
      const nextBoundary = rest.search(/\n## |\n-{3}/);
      if (nextBoundary >= 0) {
        content = content.slice(0, afterHeader + nextBoundary)
          + entry + '\n'
          + content.slice(afterHeader + nextBoundary);
      } else {
        // 没有边界，追加到末尾
        content = content.trimEnd() + '\n' + entry + '\n';
      }
    } else {
      // 段落不存在：在结尾 --- 前新建段落
      const closeIdx = content.lastIndexOf('\n---');
      if (closeIdx >= 0) {
        content = content.slice(0, closeIdx + 1)
          + `\n${sectionHeader}\n\n${entry}\n\n`
          + content.slice(closeIdx + 1);
      } else {
        content += `\n${sectionHeader}\n\n${entry}\n`;
      }
    }

    await this.app.vault.modify(file, content);
  }

  /** 追加一个 session 到每日日志（改为复用 appendToLog） */
  async appendSession(session: Session): Promise<void> {
    const entry = `- **${session.task || 'Untitled'}** — ${session.duration}min (${session.preset}) | ${session.start} → ${session.end}`;
    await this.appendToLog('Sessions', entry);
  }

  /** 追加已完成任务到每日日志 */
  async appendCompletedTask(text: string): Promise<void> {
    const now = new Date();
    const time = `${String(now.getHours()).padStart(2, '0')}:${String(now.getMinutes()).padStart(2, '0')}`;
    await this.appendToLog('Completed Tasks', `- [x] ${text} ✅ ${time}`);
  }

  /** 追加已完成 GTD 条目到每日日志 */
  async appendCompletedGtd(text: string): Promise<void> {
    const now = new Date();
    const time = `${String(now.getHours()).padStart(2, '0')}:${String(now.getMinutes()).padStart(2, '0')}`;
    await this.appendToLog('Completed GTD', `- [x] ${text} ✅ ${time}`);
  }

  /** 加载今日 session 记录 */
  async loadTodaySessions(): Promise<Session[]> {
    const path = this.getLogPath();
    const file = this.app.vault.getAbstractFileByPath(path) as TFile | null;
    if (!file) return [];

    const content = await this.app.vault.read(file);
    const sessions: Session[] = [];

    // 解析 `**task** — durationmin (preset) | start → end`
    const re = /\*\*(.+?)\*\*\s*—\s*(\d+)min\s*\((.+?)\)\s*\|\s*(.+?)\s*→\s*(.+)/g;
    let match;
    while ((match = re.exec(content)) !== null) {
      sessions.push({
        task: match[1] === 'Untitled' ? '' : match[1],
        duration: parseInt(match[2]),
        preset: match[3],
        start: match[4].trim(),
        end: match[5].trim(),
      });
    }
    return sessions;
  }

  // ═══════════════════════ GTD Board ═══════════════════

  getGtdPath(): string {
    return `${this.settings.exportPath || 'Pomodoro Logs'}/GTD Board.md`;
  }

  async saveGtdItems(items: GtdItem[]): Promise<void> {
    await this.ensureFolder();
    const path = this.getGtdPath();
    let file = this.app.vault.getAbstractFileByPath(path) as TFile | null;

    const cols: { key: string; label: string }[] = [
      { key: 'inbox', label: 'Capture' },
      { key: 'clarify', label: 'Clarify' },
      { key: 'next', label: 'Next Actions' },
      { key: 'doing', label: 'Doing' },
    ];

    let md = `# GTD Board\n\n> Auto-saved by Pomodoro\n\n`;
    for (const col of cols) {
      const colItems = items.filter(i => i.col === col.key);
      md += `## ${col.label}\n\n`;
      if (colItems.length === 0) {
        md += `—\n\n`;
      } else {
        for (const item of colItems) {
          md += `- [ ] ${item.text}\n`;
        }
        md += '\n';
      }
    }

    if (!file) {
      await this.app.vault.create(path, md);
    } else {
      await this.app.vault.modify(file, md);
    }
  }

  async loadGtdItems(): Promise<GtdItem[]> {
    const path = this.getGtdPath();
    const file = this.app.vault.getAbstractFileByPath(path) as TFile | null;
    if (!file) return [];

    const content = await this.app.vault.read(file);
    const items: GtdItem[] = [];
    let idCounter = 0;

    const colMap: Record<string, string> = {
      'capture': 'inbox',
      'clarify': 'clarify',
      'next actions': 'next',
      'doing': 'doing',
    };

    // 按 ## 标题分组
    const sections = content.split(/^## /gm);
    for (const section of sections) {
      const lines = section.split('\n');
      const header = lines[0].trim().toLowerCase();
      const col = colMap[header];
      if (!col) continue;

      for (let i = 1; i < lines.length; i++) {
        const m = lines[i].match(/^- \[.\] (.+)$/);
        if (m) {
          items.push({ id: idCounter++, text: m[1].trim(), col: col as GtdItem['col'] });
        }
      }
    }

    return items;
  }

  // ═══════════════════════ Tasks ═══════════════════

  getTasksPath(): string {
    return `${this.settings.exportPath || 'Pomodoro Logs'}/Tasks.md`;
  }

  async saveTasks(tasks: TaskItem[]): Promise<void> {
    await this.ensureFolder();
    const path = this.getTasksPath();
    let file = this.app.vault.getAbstractFileByPath(path) as TFile | null;

    let md = `# Tasks\n\n> Auto-saved by Pomodoro\n\n`;
    if (tasks.length === 0) {
      md += `_No tasks._\n`;
    } else {
      for (const t of tasks) {
        md += `- [ ] ${t.text}${t.est > 1 ? ` (${t.est}p)` : ''}\n`;
      }
    }

    if (!file) {
      await this.app.vault.create(path, md);
    } else {
      await this.app.vault.modify(file, md);
    }
  }

  async loadTasks(): Promise<TaskItem[]> {
    const path = this.getTasksPath();
    const file = this.app.vault.getAbstractFileByPath(path) as TFile | null;
    if (!file) return [];

    const content = await this.app.vault.read(file);
    const tasks: TaskItem[] = [];
    let idCounter = 0;

    const lines = content.split('\n');
    for (const line of lines) {
      const m = line.match(/^- \[.\] (.+?)(?: \((\d+)p\))?\s*$/);
      if (m) {
        tasks.push({
          id: idCounter++,
          text: m[1].trim(),
          est: parseInt(m[2]) || 1,
        });
      }
    }

    return tasks;
  }
}
